# Generated by Django 4.0.4 on 2022-11-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_lang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField()),
                ('designation', models.CharField(max_length=50)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.language')),
            ],
        ),
    ]
